modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"

[[mods]]
modId="astromaterials"
version="0.1"
displayName="Astro Materials"
credits="Created using MCreator: https://mcreator.net/about"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/astro-materials"
logoFile="logo.png"
authors="JoseFrijolito"

[[dependencies.astromaterials]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




